Repository PromptPlace/PromptPlace_BE, pull requests merged in 2025-07, with the labels that each got.

#4 [feat/#2]네이버 로그인/회원가입 구현 및 로직 분할
  package.json
  pnpm-lock.yaml
  src/config/passport.ts
  src/config/social/google.ts
  src/config/social/naver.ts
  src/routes/auth.ts
  src/routes/auth/google.ts
  src/routes/auth/naver.ts
Labels: enhancement

#21 feat: 회원탈퇴 로직 구현
  src/config/passport.ts
  src/config/prisma.ts
  src/index.ts
  src/members/controllers/member.controller.ts
  src/members/repositories/member.repository.ts
  src/members/routes/member.route.ts
  src/members/services/member.service.ts
  src/routes/auth.ts
Labels: enhancement

#29 feat: UserImage 테이블 생성 및 image 등록 구현
  package.json
  pnpm-lock.yaml
  prisma/migrations/20250720113136_add_user_image/migration.sql
  prisma/schema.prisma
  src/members/controllers/member.controller.ts
  src/members/repositories/member.repository.ts
  src/members/routes/member.route.ts
  src/members/services/member.service.ts
  src/middlewares/responseHandler.ts
  src/middlewares/upload.ts
  uploads/1753012119706.jpg
Labels: enhancement

#33 Feat/#9
  src/index.ts
  src/prompts/routes/prompt.downlaod.route.ts
  src/prompts/services/prompt.download.service.ts
Labels: enhancement

#36 feat: 회원 정보 불러오기 구현
  src/members/controllers/member.controller.ts
  src/members/repositories/member.repository.ts
  src/members/routes/member.route.ts
  src/members/services/member.service.ts
Labels: enhancement

#38 Feat: 프롬프트 찜 취소하기 API 구현
  src/prompts/controllers/prompt.like.controller.ts
  src/prompts/repositories/prompt.like.repository.ts
  src/prompts/routes/prompt.like.route.ts
  src/prompts/services/prompt.like.service.ts
Labels: enhancement

#61 Feat: 회원 팔로우, 언팔로우 기능 구현
  src/members/controllers/member.controller.ts
  src/members/repositories/member.repository.ts
  src/members/routes/member.route.ts
  src/members/services/member.service.ts
Labels: enhancement

#63 [FIX]: 리뷰 수정하기 응답 구조 수정, 속성 추가(#62)
  src/reviews/controllers/review.controller.ts
  src/reviews/dtos/review.dtos.ts
Labels: fix

#70 Feat: 회원 팔로잉, 팔로우 목록 조회
  src/members/controllers/member.controller.ts
  src/members/dtos/follower.dto.ts
  src/members/repositories/member.repository.ts
  src/members/routes/member.route.ts
  src/members/services/member.service.ts
Labels: enhancement

#75 feat: 문의하기 구현
  src/index.ts
  src/inquiries/controllers/inquiry.controller.ts
  src/inquiries/dtos/create-inquiry.dto.ts
  src/inquiries/repositories/inquiry.repository.ts
  src/inquiries/routes/inquiry.route.ts
  src/inquiries/services/inquiry.service.ts
Labels: enhancement

#80 feat: 내가 받은 리뷰 목록 구현(#66)
  src/reviews/controllers/review.controller.ts
  src/reviews/dtos/review.dtos.ts
  src/reviews/repositories/review.repository.ts
  src/reviews/routes/review.route.ts
  src/reviews/services/review.service.ts
Labels: enhancement, fix

#81 refactor: accessToken 유효시간 1h -> 3h
  src/auth/services/auth.service.ts
Labels: refactor

#85 feat: 관리자 리뷰 삭제 조치(#82)
  src/reviews/repositories/review.repository.ts
  src/reviews/routes/review.route.ts
  src/reviews/services/review.service.ts
Labels: enhancement

#88 Chore: 프론트엔드 CORS 허용
  package.json
  pnpm-lock.yaml
  src/index.ts
Labels: enhancement

#90 feat: 문의 상세보기 구현
  package.json
  pnpm-lock.yaml
  src/inquiries/controllers/inquiry.controller.ts
  src/inquiries/repositories/inquiry.repository.ts
  src/inquiries/routes/inquiry.route.ts
  src/inquiries/services/inquiry.service.ts
  src/routes/routes.ts
  tsoa.json
Labels: enhancement

#98 fix: migration 기록 초기화
  prisma/migrations/0_init/migration.sql
  prisma/migrations/20250709151206_change_bigint_to_int/migration.sql
  prisma/migrations/20250715040510_change_announcement/migration.sql
  prisma/migrations/20250718041147_add_download_url_to_prompt/migration.sql
  prisma/migrations/20250718050903_add_prompt_likes/migration.sql
  prisma/migrations/20250718190756_add_refresh_token/migration.sql
  prisma/migrations/20250720113136_add_user_image/migration.sql
  prisma/migrations/20250721065406_add_unique_constraint_to_user_email/migration.sql
  prisma/migrations/20250722075218_separate_user_profile/migration.sql
  prisma/migrations/20250722075354_change_user_history_to_one_to_many/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
Labels: fix

#101 [FEAT] 문의 답변하기, 문의 읽음 처리
  src/inquiries/controllers/inquiry.controller.ts
  src/inquiries/dtos/create-reply.dto.ts
  src/inquiries/repositories/inquiry.repository.ts
  src/inquiries/routes/inquiry.route.ts
  src/inquiries/services/inquiry.service.ts
Labels: enhancement

#102 FEAT: 신고 등록하기 (#92)
  package.json
  pnpm-lock.yaml
  prisma/migrations/20250729142713_change_report_structure/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  src/index.ts
  src/reports/controllers/report.controller.ts
  src/reports/dtos/report.dto.ts
  src/reports/repositories/report.repository.ts
  src/reports/routes/report.route.ts
  src/reports/services/report.service.ts
Labels: enhancement
