Repository PromptPlace/PromptPlace_BE, pull requests merged in 2025-08, with the labels that each got.

#118 [FEAT] 새 공지사항, 신고 접수 알림 생성(#112)
  prisma/migrations/20250731113727_change_notification_model/migration.sql
  prisma/migrations/20250731195349_make_user_id_nullable_in_notification/migration.sql
  prisma/schema.prisma
  src/announcements/controllers/announcement.controller.ts
  src/announcements/services/announcement.service.ts
  src/config/eventBus.ts
  src/index.ts
  src/notifications/controllers/notification.controller.ts
  src/notifications/dtos/notification.dto.ts
  src/notifications/listeners/notification.listener.ts
  src/notifications/repositories/notification.repository.ts
  src/notifications/routes/notification.route.ts
  src/notifications/services/notification.service.ts
  src/reports/services/report.service.ts
  src/reviews/controllers/review.controller.ts
  src/reviews/dtos/review.dto.ts
  src/reviews/services/review.service.ts
Labels: enhancement

#120 Docs/#103
  docs/index.html
  docs/swagger.json
  package.json
  pnpm-lock.yaml
  scripts/generate-swagger.ts
Labels: documentation

#123 fix: AppError.ts 에러 해결
  src/inquiries/controllers/inquiry.controller.ts
  src/inquiries/dtos/create-inquiry.dto.ts
  src/inquiries/services/inquiry.service.ts
  src/members/controllers/member.controller.ts
Labels: fix

#124 fix: follower.dto linter 오류 해결
  src/members/dtos/follower.dto.ts
Labels: fix

#126 [FEAT]: 새로운 팔로워 알림 생성 구현(#125)
  src/members/services/member.service.ts
  src/notifications/listeners/notification.listener.ts
  src/notifications/repositories/notification.repository.ts
  src/notifications/services/notification.service.ts
Labels: enhancement

#132 [FEAT] 새 프롬프트 알림 생성 구현(#131)
  src/notifications/listeners/notification.listener.ts
  src/notifications/repositories/notification.repository.ts
  src/notifications/services/notification.service.ts
  src/prompts/services/prompt.service.ts
Labels: enhancement

#147 feat:카카오 회원가입/로그인 구현 & 회원가입 API 구현
  package-lock.json
  package.json
  src/auth/controllers/auth.controller.ts
  src/auth/dtos/complete-signup.dto.ts
  src/auth/routes/auth.route.ts
  src/auth/routes/social/kakao.ts
  src/auth/services/auth.service.ts
  src/config/passport.ts
  src/config/social/kakao.ts
Labels: enhancement

#148 Feat: 메시지 목록 조회 API 구현
  pnpm-lock.yaml
  src/messages/controllers/message.controller.ts
  src/messages/repositories/message.repository.ts
  src/messages/routes/message.route.ts
  src/messages/services/message.service.ts
Labels: enhancement

#149 Feat: 메시지 삭제 API 구현
  src/messages/controllers/message.controller.ts
  src/messages/routes/message.route.ts
  src/messages/services/message.service.ts
Labels: enhancement

#150 Feat: 메시지 읽음 처리 API 구현
  src/messages/controllers/message.controller.ts
  src/messages/routes/message.route.ts
  src/messages/services/message.service.ts
Labels: enhancement

#157 [BUG]: complete-signup.dto 초기화 에러 수정(#156)
  dist/auth/controllers/auth.controller.js
  dist/auth/dtos/complete-signup.dto.js
  dist/auth/routes/auth.route.js
  dist/auth/routes/social/kakao.js
  dist/auth/services/auth.service.js
  dist/config/passport.js
  dist/config/social/kakao.js
  dist/index.js
  dist/inquiries/controllers/inquiry.controller.js
  dist/inquiries/services/inquiry.service.js
  dist/messages/controllers/message.controller.js
  dist/messages/dtos/message.dto.js
  dist/messages/repositories/message.repository.js
  dist/messages/routes/message.route.js
  dist/messages/services/message.service.js
  dist/notifications/controllers/notification.controller.js
  dist/notifications/dtos/notification.dto.js
  dist/notifications/listeners/notification.listener.js
  dist/notifications/repositories/notification.repository.js
  dist/notifications/routes/notification.route.js
  dist/notifications/services/notification.service.js
  dist/prompts/controllers/prompt.controller.js
  dist/prompts/repositories/prompt.repository.js
  dist/prompts/services/prompt.download.service.js
  dist/prompts/services/prompt.service.js
  dist/purchases/controller/purchase.request.controller.js
  dist/purchases/dtos/purchase.request.dto.js
  dist/purchases/repositories/purchase.request.repository.js
  dist/purchases/routes/purchase.request.route.js
  dist/purchases/services/purchase.request.service.js
  dist/reviews/controllers/review.controller.js
  src/auth/dtos/complete-signup.dto.ts
Labels: bug

#160 Chore: CORS 설정 추가
  src/index.ts
Labels: fix

#163 Document/#162
  src/reviews/controllers/review.controller.ts
  src/reviews/routes/review.route.ts
Labels: documentation

#169 Fix/#168 특정 회원 정보 조회 및 이력 조회 API 접근 권한 수정
  src/members/services/member.service.ts
Labels: fix

#171 fix: 회원 이력 조회 로직 변경
  src/members/services/member.service.ts
Labels: fix

#173 feat: 소셜 로그인 토큰 교환 API 구현 및 프론트엔드 연동 준비 완료
  src/auth/controllers/auth.controller.ts
  src/auth/dtos/complete-signup.dto.ts
  src/auth/services/auth.service.ts
Labels: enhancement

#178 feat: 소셜 로그인 토큰 교환 API 구현
  src/auth/controllers/auth.controller.ts
  src/auth/routes/auth.route.ts
Labels: enhancement

#196 [BUG] cors설정에 IP주소 추가
  src/index.ts
Labels: bug

#203 Feat: 결제 내역 조회 API 구현
  src/purchases/controller/purchase.controller.ts
  src/purchases/dtos/purchase.dto.ts
  src/purchases/repositories/purchase.request.repository.ts
  src/purchases/routes/purchase.request.route.ts
  src/purchases/services/purchase.service.ts
Labels: enhancement

#204 Fix: Message 프리즈마 수정
  prisma/schema.prisma
Labels: bug

#210 Feat: 출금 가능 금액 조회 API 구현
  src/withdrawals/controllers/withdrawal.available.controller.ts
  src/withdrawals/dtos/withdrawal.available.dto.ts
  src/withdrawals/repositories/withdrawal.repository.ts
  src/withdrawals/routes/withdrawal.route.ts
  src/withdrawals/services/withdrawal.available.service.ts
  src/withdrawals/services/withdrawal.service.ts
Labels: enhancement

#218 Fix/#217
  src/config/social/google.ts
  src/config/social/kakao.ts
  src/config/social/naver.ts
  src/index.ts
  src/members/controllers/member.controller.ts
  src/members/repositories/member.repository.ts
  src/members/routes/member.route.ts
  src/members/services/member.service.ts
  src/middlewares/upload.ts
Labels: fix

#221 Fix: 출금 요청 로직 수정
  prisma/migrations/20250814_baseline_from_prod/migration.sql
  prisma/schema.prisma
  src/withdrawals/controllers/withdrawal.controller.ts
  src/withdrawals/dtos/withdrawal.dto.ts
  src/withdrawals/services/withdrawal.service.ts
Labels: fix

#226 Feat: 계좌 등록 API 구현
  prisma/schema.prisma
  src/accounts/controllers/account.controller.ts
  src/accounts/dtos/account.dto.ts
  src/accounts/repositories/account.repository.ts
  src/accounts/routes/account.route.ts
  src/accounts/services/account.service.ts
  src/index.ts
Labels: enhancement

#227 [FIX] 특정 프롬프트 리뷰 불러오기 응답 API 수정
  src/reviews/dtos/review.dto.ts
  src/reviews/repositories/review.repository.ts
  src/reviews/routes/review.route.ts
  src/reviews/services/review.service.ts
Labels: fix

#233 Feat: 계좌 정보 불러오기 API 구현
  src/accounts/controllers/account.controller.ts
  src/accounts/dtos/account.dto.ts
  src/accounts/repositories/account.repository.ts
  src/accounts/routes/account.route.ts
  src/accounts/services/account.service.ts
Labels: enhancement

#234 fix: 팔로워, 팔로잉 목록 조회 시 팔로워 수 반환 응답 추가
  src/config/passport.ts
  src/members/repositories/member.repository.ts
  src/members/routes/member.route.ts
  src/members/services/member.service.ts
Labels: fix

#236 fix: 특정 회원 조회하기 API 토큰 인증 제거
  src/members/controllers/member.controller.ts
  src/members/routes/member.route.ts
  src/members/services/member.service.ts
Labels: fix

#238 fix: accessToken 3h -> 24h
  src/auth/services/auth.service.ts
Labels: fix

#244 fix: 회원 탈퇴 로직 수정
  src/config/social/google.ts
  src/config/social/naver.ts
Labels: fix

#245 [FEAT]: 프롬프터 알림 구독 여부 조회 api 구현
  src/notifications/controllers/notification.controller.ts
  src/notifications/dtos/notification.dto.ts
  src/notifications/routes/notification.route.ts
  src/notifications/services/notification.service.ts
Labels: enhancement

#250 [FIX]: 구독여부 응답 필드 변경(#247)
  src/notifications/dtos/notification.dto.ts
  src/notifications/services/notification.service.ts
Labels: fix

#258 fix/#257 400에러 응답값 수정
  src/inquiries/dtos/create-inquiry.dto.ts
  src/members/controllers/member.controller.ts
  src/members/dtos/create-sns.dto.ts
Labels: fix

#262 bug: 회원 정보 로그아웃, 로그인 시에도 유지
  src/auth/services/auth.service.ts
Labels: bug

#263 bug: 회원 정보 수정 후 로그아웃하면 정보 없어지는 버그
  src/auth/services/auth.service.ts
Labels: bug

#267 fix: 401 Unauthorized 전역 에러로 등록
  src/middlewares/errorHandler.ts
Labels: fix

#269 FIX: 한줄 소개 PATCH 빈 문자열 허용
  src/members/dtos/update-intro.dto.ts
Labels: fix
